# Generated by Django 5.0 on 2023-12-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_pagina', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='directivo',
            new_name='directivos',
        ),
        migrations.RenameModel(
            old_name='empleado',
            new_name='empleados',
        ),
    ]
